# Generated by Django 5.0.3 on 2024-03-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='Apellidos',
            field=models.CharField(default='valor_predeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='Carnet',
            field=models.CharField(default='valor_predeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='Nombres',
            field=models.CharField(default='valor_predeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='correoElectronico',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='task',
            name='fechaNacimiento',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
